### ISSUE TITLE
how to use multiple devices for SpdkLVStore engine

### ISSUE THREAD

**Issue by sjp00556** [eosphoros-ai/liteio#18]
1. with aioBdev type, it can only add one device. how to set multi devices to a storage pool? 
2. with raidBdev type, it makes raid0 for all of nvme devices. can i use partly nvme disks to make raid0 and create a storage pool? 
3. if i use multi disks in one storage pool, if one disk is damaged, dose it mean that the storage pool is unavaliable?

**Comment by silentred** [comment]
1. aioBdev is typically used with LVM volume, in case of sharing a LVM volume to a remote host through SPDK. The steps include creating a LV, creating an aioBdev based on it, creating a subsytem to share the aioBdev.
2. It is recommended to manually create the VG or LVS if you want to use partial disks on the host. If the agent finds the pool by the configured name, it will use the pool to provision volumes.
3. Generally, yes. The reason is that most infra providers do not offer options of replacing disks. The operation granularity is usually VM.

**Comment by sjp00556** [comment]
@silentred  the explanation is very clear, thanks a lot!
